In [1]:
import pandas as pd
df = pd.read_excel("data echo.xlsx")

In [2]:
df

,Echo of Input Data,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,RAM Manager,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,15.03.00.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,HFH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,DataBase: 14136 - 222 Milwaukee 2016.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Building Code: IBC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2017-02-02 11:39:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Layout Types:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,P1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,LEVEL 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,LEVEL 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,MEZZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,LEVEL 3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,LEVEL 5-7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,LEVEL 8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,ROOF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,MECH ROOF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,LEVEL 4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,P2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,LEVEL 7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,LEVEL 6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,LEVEL 5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,ROOF CONCEPT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Tables Selected:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Deck Table:,ramdecks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Master Steel Table:,ramaisc,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Default Steel Table:,ramaisc,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Alternate Steel Table:,ramaisc,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Column Steel Table:,ramaisc,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Reinforcement Table:,ramastm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
4070,NaN,NaN,NaN,NaN,156,34,NaN,NaN,NaN,NaN,NaN
4071,NaN,NaN,NaN,NaN,119.25,34,NaN,NaN,NaN,NaN,NaN
4072,NaN,NaN,NaN,NaN,119.25,33.5,NaN,NaN,NaN,NaN,NaN
4073,Concrete,15,Two-Way,--,156,32,NaN,NaN,NaN,NaN,NaN
4074,NaN,NaN,NaN,NaN,190,32,NaN,NaN,NaN,NaN,NaN
4075,NaN,NaN,NaN,NaN,190,34,NaN,NaN,NaN,NaN,NaN
4076,NaN,NaN,NaN,NaN,156,34,NaN,NaN,NaN,NaN,NaN
4077,NaN,NaN,NaN,NaN,156,32,NaN,NaN,NaN,NaN,NaN
4078,Concrete,15,Two-Way,--,156,52,NaN,NaN,NaN,NaN,NaN
4079,NaN,NaN,NaN,NaN,190,52,NaN,NaN,NaN,NaN,NaN
4080,NaN,NaN,NaN,NaN,190,54,NaN,NaN,NaN,NaN,NaN
4081,NaN,NaN,NaN,NaN,156,54,NaN,NaN,NaN,NaN,NaN
4082,NaN,NaN,NaN,NaN,156,52,NaN,NaN,NaN,NaN,NaN
4083,Concrete,15,Two-Way,--,47,-1,NaN,NaN,NaN,NaN,NaN
4084,NaN,NaN,NaN,NaN,190,-1,NaN,NaN,NaN,NaN,NaN
4085,NaN,NaN,NaN,NaN,190,1,NaN,NaN,NaN,NaN,NaN
4086,NaN,NaN,NaN,NaN,156.75,1,NaN,NaN,NaN,NaN,NaN
4087,NaN,NaN,NaN,NaN,156.75,0,NaN,NaN,NaN,NaN,NaN
4088,NaN,NaN,NaN,NaN,155.25,0,NaN,NaN,NaN,NaN,NaN
4089,NaN,NaN,NaN,NaN,155.25,1,NaN,NaN,NaN,NaN,NaN
4090,NaN,NaN,NaN,NaN,120.73,1,NaN,NaN,NaN,NaN,NaN
4091,NaN,NaN,NaN,NaN,120.75,0.02,NaN,NaN,NaN,NaN,NaN
4092,NaN,NaN,NaN,NaN,119.25,-0.02,NaN,NaN,NaN,NaN,NaN
4093,NaN,NaN,NaN,NaN,119.23,1,NaN,NaN,NaN,NaN,NaN
4094,NaN,NaN,NaN,NaN,84.75,1,NaN,NaN,NaN,NaN,NaN
4095,NaN,NaN,NaN,NaN,84.75,0,NaN,NaN,NaN,NaN,NaN
4096,NaN,NaN,NaN,NaN,83.25,0,NaN,NaN,NaN,NaN,NaN
4097,NaN,NaN,NaN,NaN,83.25,1,NaN,NaN,NaN,NaN,NaN
4098,NaN,NaN,NaN,NaN,47,1,NaN,NaN,NaN,NaN,NaN
4099,NaN,NaN,NaN,NaN,47,-1,NaN,NaN,NaN,NaN,NaN

In [15]:
firstColumn = df.iloc[:,0]

In [16]:
firstColumn

0                                   RAM Manager
1                                  15.03.00.000
2                                           HFH
3       DataBase: 14136 - 222 Milwaukee 2016.12
4                            Building Code: IBC
5                                           NaN
6                           2017-02-02 11:39:00
7                                 Layout Types:
8                                            P1
9                                       LEVEL 1
10                                      LEVEL 2
11                                         MEZZ
12                                      LEVEL 3
13                                    LEVEL 5-7
14                                      LEVEL 8
15                                         ROOF
16                                    MECH ROOF
17                                      LEVEL 4
18                                           P2
19                                      LEVEL 7
20                                      LEVEL 6
21                                      LEVEL 5
22                                 ROOF CONCEPT
23                             Tables Selected:
24                                  Deck Table:
25                          Master Steel Table:
26                         Default Steel Table:
27                       Alternate Steel Table:
28                          Column Steel Table:
29                         Reinforcement Table:
                         ...
4070                                        NaN
4071                                        NaN
4072                                        NaN
4073                                   Concrete
4074                                        NaN
4075                                        NaN
4076                                        NaN
4077                                        NaN
4078                                   Concrete
4079                                        NaN
4080                                        NaN
4081                                        NaN
4082                                        NaN
4083                                   Concrete
4084                                        NaN
4085                                        NaN
4086                                        NaN
4087                                        NaN
4088                                        NaN
4089                                        NaN
4090                                        NaN
4091                                        NaN
4092                                        NaN
4093                                        NaN
4094                                        NaN
4095                                        NaN
4096                                        NaN
4097                                        NaN
4098                                        NaN
4099                                        NaN
Name: Echo of Input Data, Length: 4100, dtype: object

In [55]:
levelsHeader = None
tablesSelectedHeader = None
for x in firstColumn:
    if x == "Layout Types:":
        print("Got it")
        print(list(firstColumn).index("Layout Types:"))
        levelsHeader = firstColumn[firstColumn =="Layout Types:"].index[0]
    if x == "Tables Selected:":
        tablesSelectedHeader = firstColumn[firstColumn =="Tables Selected:"].index[0]

Got it
7

In [56]:
levels = firstColumn[levelsHeader+1:tablesSelectedHeader]

In [57]:
print(levels)

8               P1
9          LEVEL 1
10         LEVEL 2
11            MEZZ
12         LEVEL 3
13       LEVEL 5-7
14         LEVEL 8
15            ROOF
16       MECH ROOF
17         LEVEL 4
18              P2
19         LEVEL 7
20         LEVEL 6
21         LEVEL 5
22    ROOF CONCEPT
Name: Echo of Input Data, dtype: object

In [62]:
storyDataHeader = firstColumn[firstColumn =="Story Data:"].index[0]+2

In [63]:
levelsToHeightDictStart = storyDataHeader + 2

In [75]:
print(levelsToHeightDictStart)
print(storyDataHeader)
print(len(levels))

35
33
15

In [86]:
levelsToHeight_df=df.iloc[storyDataHeader:storyDataHeader+len(levels)-2,3:5]

In [87]:
levelsToHeight_df

   Unnamed: 3 Unnamed: 4
33  MECH ROOF     11.833
34       ROOF     13.833
35    LEVEL 8      9.833
36    LEVEL 7      9.833
37    LEVEL 6      9.833
38    LEVEL 5      9.833
39    LEVEL 4      9.833
40    LEVEL 3         18
41    LEVEL 2         11
42       MEZZ         11
43    LEVEL 1     12.333
44         P1     13.583
45         P2      7.417